### ISSUE TITLE
starting instructions

### ISSUE THREAD

**Issue by retog** [zazukoians/trifid-ld#3] opened 2015-04-05 21:12 UTC
To start it with iojs (using https://github.com/iojs/docker-iojs) I had to enter the following commands 

```
npm install
iojs index.html
```

without the first it would complain about missing modules.

What to do after starting it is not clear, I would like to see what it can do using the default data. I figured that I had to replace localhost:8080 with the actual host and port in `node_modules/tbbt-ld/dist/tbbt.nt`. Now I can get some turtle at http://172.17.0.40:8080/data/person/stuart-bloom. But I can't access the simple HTML interface the readme mentions. Tried replacing `localhost` with `127.17.0.40` in config.js, but this didn't made any difference.

**Comment by ktk** [comment] 2015-04-06 08:58
I can reproduce that here, looks like the HTML interface got broken with the last update.

Also I need to give some more explanation in the readme regarding changing ports & sample URIs

@bergos any ideas?

**Comment by bergos** [comment] 2015-04-06 19:52
Trifid maps the namespace on the fly. That function contained a default hostname `localhost`. That could have been a little bit confusing. I moved the default value in that function to the configuration. https://github.com/zazukoians/trifid-ld/commit/8dc48b9b917b0a7cb833954e8bc82359cd34b975

**Comment by retog** [comment] 2015-04-09 11:55
Still not so clear, when does one has to change the value of "hostname"
when one wants trifid to listen to another hostname or when one wants to
have the backing RDF using a differen hostname in the URIs?

**Comment by ktk** [comment] 2015-05-26 18:10
After investigating the broken HTML output we narrowed it down to this:

```
[2015-05-26T18:05:12.612Z]  INFO: trifid-ld/18131 on sdf.local: handle GET request for IRI <http://localhost:8080/data/person/amy-farrah-fowler>
    script: /Users/sdf/tmp/trifid-ld/lib/render-html-middleware.js
[2015-05-26T18:05:12.625Z] ERROR: trifid-ld/18131 on sdf.local:
    TypeError: Cannot use 'in' operator to search for 'Access-Control-Allow-Origin' in null
        at /Users/sdf/tmp/trifid-ld/config.js:65:25
        at Array.forEach (native)
        at Object.patchResponseHeaders [as patchResponse] (/Users/sdf/tmp/trifid-ld/config.js:64:17)
        at ServerResponse.res.writeHead (/Users/sdf/tmp/trifid-ld/lib/patch-headers-middleware.js:23:25)
        at ServerResponse._implicitHeader (_http_server.js:172:8)
        at ServerResponse.OutgoingMessage.end (_http_outgoing.js:529:10)
        at /Users/sdf/tmp/trifid-ld/lib/render-html-middleware.js:64:21
        at invokeCallback (/Users/sdf/tmp/trifid-ld/node_modules/es6-promise/dist/commonjs/promise/promise.js:53:15)
        at publish (/Users/sfd/tmp/trifid-ld/node_modules/es6-promise/dist/commonjs/promise/promise.js:98:5)
        at publishFulfillment (/Users/sdf/tmp/trifid-ld/node_modules/es6-promise/dist/commonjs/promise/promise.js:204:3)
    --
    script: /Users/sdf/tmp/trifid-ld/lib/render-html-middleware.js
```

**Comment by bergos** [comment] 2015-06-30 09:13
fixed in the latest version

**Closed as completed by bergos** 2015-06-30 09:13 UTC
